from pathlib import Path
from html import escape
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent
EMAIL = "info@adam-jakubowski.com"
LANGS = ("pl", "en", "de")

PATHS = {
    "home": ("index.html", "index.html", "index.html"),
    "private": ("dla-klienta-prywatnego.html", "private-clients.html", "privatkunden.html"),
    "business": ("dla-firm.html", "for-companies.html", "fuer-unternehmen.html"),
    "process": ("proces.html", "process.html", "arbeitsweise.html"),
    "proof": ("dowody.html", "evidence.html", "nachweise.html"),
    "about": ("o-mnie.html", "about.html", "ueber-mich.html"),
    "contact": ("kontakt.html", "contact.html", "kontakt.html"),
    "b2c_form": ("formularz-b2c.html", "b2c-form.html", "b2c-formular.html"),
    "b2b_form": ("formularz-b2b.html", "b2b-form.html", "b2b-formular.html"),
    "privacy": ("polityka-prywatnosci.html", "privacy.html", "datenschutz.html"),
    "faq": ("faq.html", "faq.html", "faq.html"),
    "thanks": ("dziekuje.html", "thank-you.html", "danke.html"),
    "sample_report": ("sample-handover-report.html", "sample-handover-report.html", "sample-handover-report.html"),
    "checklist": ("pre-order-checklist.html", "pre-order-checklist.html", "pre-order-checklist.html"),
    "risk_register": ("sample-risk-register.html", "sample-risk-register.html", "sample-risk-register.html"),
}

def filename(key, lang):
    return PATHS[key][LANGS.index(lang)]

def url(key, lang):
    return f"/{lang}/" if key == "home" else f"/{lang}/{filename(key, lang).removesuffix('.html')}"

T = {
"pl": {
"home":"Start", "private":"Dla klienta prywatnego", "business":"Dla firm", "process":"Jak pracuję", "proof":"Doświadczenie i materiały", "about":"O mnie", "contact":"Opisz swoją sytuację", "privacy":"Polityka prywatności",
"skip":"Przejdź do treści", "menu":"Menu", "footer":"Prowadzenie i kontrola realizacji mebli na wymiar oraz fit-out · Konin · PL/EN/DE", "footnote":"Zakres i granice odpowiedzialności ustalamy na piśmie przed rozpoczęciem pracy.",
"eyebrow":"PROWADZENIE REALIZACJI / MEBLE NA WYMIAR / FIT-OUT", "hero":"Spokojniejsza realizacja. Jasne decyzje. Udokumentowany odbiór.", "lead":"Prowadzę i kontroluję realizacje mebli na wymiar oraz fit-out dla klientów prywatnych i firm. Porządkuję zakres, ryzyka, decyzje, jakość, montaż i odbiór — bez przejmowania roli projektanta lub wykonawcy.",
"b2c_cta":"Chcę omówić realizację mebli", "b2b_cta":"Szukam wsparcia dla firmy", "two_paths":"Dwie ścieżki. Ten sam standard kontroli.", "private_lead":"Pomagam sprawdzić ofertę i zakres, przygotować pytania do wykonawcy oraz udokumentować montaż, odbiór i poprawki. Konin + 50 km; dalej po uzgodnieniu.", "business_lead":"Łączę dokumentację, produkcję, logistykę, gotowość miejsca, montaż i odbiór w kontrolowany proces. Wsparcie w PL/EN/DE.",
"proof_1":"Ponad 20 lat praktyki", "proof_1b":"w branży meblarskiej", "proof_2":"PL / EN / DE", "proof_2b":"koordynacja międzynarodowa", "proof_3":"Produkcja → odbiór", "proof_3b":"kontrola uzgodnionych etapów realizacji", "proof_4":"Pisemny rezultat", "proof_4b":"raport, rejestr lub plan działania",
"entry":"Zacznij od zamkniętego rezultatu.", "method":"Najpierw zakres. Potem kontrola.", "steps":["Kwalifikacja i dopasowanie","Pisemny rezultat, zakres i wyłączenia","Kontrola uzgodnionych punktów","Raport, rejestr decyzji lub plan działania","Formalne zamknięcie i decyzja o kolejnym kroku"],
"boundary_title":"Jasna rola od początku.", "boundary":"Nie projektuję wnętrz, nie wykonuję robót, nie wydaję opinii prawnych ani ekspertyz wymagających uprawnień. Nie gwarantuję terminu, ceny lub jakości zależnych od innych stron. Dokumentuję stan, wskazuję ryzyka i kontroluję wyłącznie zakres zapisany w ofercie. Odpowiadam za staranne wykonanie własnego uzgodnionego zakresu; ten opis nie wyłącza odpowiedzialności wymaganej prawem.", "home_cta":"Opisz sytuację — dobiorę właściwy punkt startu.",
"private_title":"Niezależna kontrola mebli na wymiar — przed zamówieniem, przy montażu i odbiorze.", "business_title":"Zewnętrzny PM dla realizacji meblowych i fit-out — od diagnozy ryzyka do zamknięcia etapu.", "services":"Usługi", "screen_title":"Sprawdzenie dopasowania przed dokumentami", "screen":"Najpierw ustalam potrzebę, zakres i oczekiwany rezultat. Przed przyjęciem poufnych dokumentów, NDA lub przygotowaniem oferty sprawdzam możliwy konflikt interesów. Jeśli wynik jest niejasny, wyjaśniam go przed dalszym krokiem.", "conf_notice":"Na pierwszym etapie wystarczy ogólny opis projektu. Nie przesyłaj poufnych dokumentów przed potwierdzeniem dopasowania i braku konfliktu interesów.",
"process_intro":"Każdy etap ma określone wejścia, rezultat, granice i moment zamknięcia.", "process_steps":[("Kwalifikacja","Segment, potrzeba, termin, dostępność i dopasowanie."),("Sprawdzenie B2B","Konflikt interesów i poufność przed przyjęciem dokumentów."),("Pisemny zakres","Rezultat, materiały wejściowe, wyłączenia, limity, cena i termin."),("Kontrolowana realizacja","Wyłącznie uzgodnione punkty; zmiana wymaga pisemnej akceptacji."),("Udokumentowany rezultat","Raport, rejestr, status gotowości albo plan działania."),("Zamknięcie","Formalne przekazanie i decyzja, czy potrzebny jest kolejny etap.")],
"about_lead":"Ponad 20 lat praktyki w branży meblarskiej: produkcja, prowadzenie zespołów, jakość, serwis i międzynarodowa koordynacja projektów.", "about_h2":"Doświadczenie od produkcji po odbiór", "about_p1":"Moje doświadczenie obejmuje kolejno pracę blisko produkcji i jakości, prowadzenie zespołów, serwis oraz koordynację projektów na rynkach międzynarodowych. Dzięki temu oceniam dokumentację przez pryzmat produkcji, logistyki i montażu.", "about_p2":"Pracuję po polsku, angielsku i niemiecku. Publicznie pokazuję tylko materiały, do których mam zgodę; pozostałe doświadczenie opisuję bez nazw klientów i danych poufnych.", "about_role":"Nie zastępuję projektanta, wykonawcy ani rzeczoznawcy. Wspieram przygotowanie i kontrolę realizacji w uzgodnionym zakresie.",
"contact_intro":"Wybierz ścieżkę. Pierwsza wiadomość jest niewiążącym zapytaniem — nie rezerwuje terminu, nie tworzy umowy i nie oznacza przyjęcia zlecenia.", "email_alt":"Wolisz krótko? Napisz bezpośrednio:", "availability_notice":"Obecnie przyjmuję wyłącznie niezobowiązujące zapytania. Do zamknięcia formalności nie zawieram umów odpłatnych, nie przyjmuję płatności i nie rezerwuję realizacji.", "territory_note":"Obsługa po polsku, angielsku lub niemiecku nie oznacza automatycznej dostępności sprzedaży za granicą. Podstawowy obszar usług to Polska; każdy projekt zagraniczny wymaga wcześniejszego potwierdzenia warunków prawnych i podatkowych.",
"form_b2c_title":"Opowiedz o swojej realizacji", "form_b2b_title":"Opisz projekt B2B", "optional":"opcjonalnie", "send_b2c":"Przygotuj wiadomość e-mail", "send_b2b":"Przygotuj wiadomość e-mail", "service":"Wybrana usługa", "select_service":"Wybieram tę usługę",
"products_b2c":[("Konsultacja przed zamówieniem","Analiza jednej oferty i dokumentacji jednej zabudowy, rozmowa do 60 minut oraz pisemna lista braków, ryzyk i pytań przesłana do 2 dni roboczych od otrzymania kompletu materiałów.","590 zł — cena końcowa"),("Asysta przy odbiorze i raport widocznego zakresu","Jedna wizyta do 2 godzin, jedna lokalizacja i jedna zabudowa; przegląd widocznych elementów i dostępnych funkcji względem przekazanej dokumentacji, zdjęcia oraz raport do 3 dni roboczych. To nie jest ekspertyza techniczna, opinia rzeczoznawcy, kontrola instalacji ani zastępstwo odbioru przez uprawnionego specjalistę.","od 990 zł — cena końcowa przed zleceniem"),("Kontrola poprawek","Jedna wizyta do 90 minut, wyłącznie pozycje z mojego raportu bazowego. Nowe usterki lub szerszy zakres wymagają osobnej wyceny.","od 590 zł — cena końcowa przed zleceniem"),("Opieka nad realizacją","Kontrola kilku uzgodnionych etapów, rejestr decyzji, ryzyk i następnych działań. Zakres godzin, wizyt i raportowania zapisuję w ofercie.","wycena indywidualna")],
"products_b2b":[("Przegląd stanu projektu","Diagnoza stanu, rejestr ryzyk i spraw otwartych, priorytety oraz plan działań na 14 lub 30 dni.","wycena indywidualna"),("Kontrola etapu","Jeden krytyczny rezultat: gotowość produkcji, wysyłki lub montażu, plan naprawczy albo zamknięcie listy.","wycena indywidualna"),("PM etapu lub projektu","Plan, rejestry decyzji i ryzyk, statusy, koordynacja punktów styku oraz formalne zamknięcie uzgodnionego zakresu.","rozliczenie etapowe lub procentowe"),("Stałe wsparcie PM","Uzgodnione bloki czasu, rezultaty i rytm raportowania — bez obietnicy stałej dostępności.","miesięczny pakiet czasu")],
"pricing_note":"Wynagrodzenie ustalam indywidualnie. Przy modelu procentowym podstawą jest wyłącznie wartość netto faktycznie koordynowanych pakietów, nie całej inwestycji. Minimalne wynagrodzenie, limit maksymalny, wyłączenia, koszty dodatkowe i zasady zmian są każdorazowo zapisane w ofercie.",
"b2c_terms":"Ceny są cenami końcowymi dla klienta prywatnego. Dojazd w Koninie jest wliczony; poza Koninem koszt wynosi 2 zł/km w obie strony, a parking i opłaty drogowe wymagają wcześniejszej akceptacji. Bezpłatna zmiana lub odwołanie terminu jest możliwe co najmniej 24 godziny wcześniej; później może zostać naliczone 50% ceny zarezerwowanej usługi i poniesione koszty dojazdu. Ustawowe prawa konsumenta pozostają bez zmian. Pełny zakres i cena są potwierdzane na piśmie przed zawarciem umowy."
},
"en": {
"home":"Home", "private":"Private clients", "business":"For companies", "process":"How I work", "proof":"Experience and materials", "about":"About", "contact":"Describe your situation", "privacy":"Privacy policy", "skip":"Skip to content", "menu":"Menu", "footer":"Custom furniture and fit-out project delivery · Konin · PL/EN/DE", "footnote":"Scope and responsibility boundaries are agreed in writing before work begins.",
"eyebrow":"PROJECT DELIVERY / CUSTOM FURNITURE / FIT-OUT", "hero":"Calmer delivery. Clear decisions. Documented handover.", "lead":"I lead and control custom furniture and fit-out delivery for private clients and companies. I structure scope, risks, decisions, quality, installation and handover — without taking over the designer’s or contractor’s role.", "b2c_cta":"Discuss my furniture project", "b2b_cta":"Find support for my company", "two_paths":"Two paths. One control standard.", "private_lead":"I help review quotations and scope, prepare questions for the contractor, and document installation, handover and corrective work. Konin + 50 km; other locations by agreement.", "business_lead":"I connect documentation, production, logistics, site readiness, installation and handover in a controlled process. Support in PL/EN/DE.",
"proof_1":"Over 20 years’ practice", "proof_1b":"in the furniture industry", "proof_2":"PL / EN / DE", "proof_2b":"international coordination", "proof_3":"Production → handover", "proof_3b":"control across the delivery path", "proof_4":"Written outcome", "proof_4b":"report, register or action plan",
"entry":"Start with a defined outcome.", "method":"Scope first. Then control.", "steps":["Qualification and fit","Written outcome, scope and exclusions","Control of agreed points","Report, decision log or action plan","Formal close-out and next-step decision"], "boundary_title":"A clear role from the start.", "boundary":"I do not design interiors, perform construction work, provide legal opinions or regulated expert services. I do not guarantee price, timing or quality controlled by other parties. I document status, identify risks and control only the written scope. I remain responsible for due care in my own agreed scope; this statement does not exclude liability required by law.", "home_cta":"Describe the situation — I will identify the right starting point.",
"private_title":"Independent control of custom furniture — before ordering, during installation and at handover.", "business_title":"External PM for custom furniture and fit-out — from risk diagnosis to stage close-out.", "services":"Services", "screen_title":"Fit check before documents", "screen":"I first establish the need, scope and expected outcome. Before accepting confidential documents, an NDA or preparing an offer, I check for a potential conflict of interest. If anything is unclear, I resolve it before the next step.", "conf_notice":"A general project description is enough at this stage. Do not send confidential documents before fit and conflict clearance.",
"process_intro":"Each stage has defined inputs, outcome, boundaries and a close-out point.", "process_steps":[("Qualification","Segment, need, timing, capacity and fit."),("B2B fit check","Conflict and confidentiality before documents."),("Written scope","Outcome, inputs, exclusions, limits, price and timing."),("Controlled execution","Only agreed points; changes require written acceptance."),("Documented outcome","Report, register, readiness status or action plan."),("Close-out","Formal handover and a decision on whether another stage is needed.")],
"about_lead":"Over 20 years of practical furniture-industry experience: production, team leadership, quality, service and international project coordination.", "about_h2":"Experience from production to handover", "about_p1":"My experience has progressed through work close to production and quality, team leadership, service and international project coordination. This lets me assess documentation through the lens of production, logistics and installation.", "about_p2":"I work in Polish, English and German. I publish only materials I am authorised to use; other experience is described without client names or confidential data.", "about_role":"I do not replace the designer, contractor or expert witness. I support preparation and control of delivery within the agreed scope.",
"contact_intro":"Choose a path. The first message is a non-binding enquiry — it does not reserve capacity, create a contract or confirm project acceptance.", "email_alt":"Prefer a short message? Email directly:", "availability_notice":"I currently accept non-binding enquiries only. Until the formal setup is complete, I do not conclude paid contracts, accept payments or reserve delivery dates.", "territory_note":"Service in Polish, English or German does not automatically mean sales are available abroad. Poland is the primary service territory; every foreign project requires prior confirmation of legal and tax conditions.", "form_b2c_title":"Tell me about your project", "form_b2b_title":"Describe your B2B project", "optional":"optional", "send_b2c":"Prepare email message", "send_b2b":"Prepare email message", "service":"Selected service", "select_service":"Choose this service",
"products_b2c":[("Pre-order consultation","Review of one quotation and the documents for one built-in, a call of up to 60 minutes and a written list of gaps, risks and questions within 2 business days after complete materials are received.","PLN 590 — final consumer price"),("Handover assistance and visible-scope report","One visit up to 2 hours, one location and one built-in; review of visible elements and accessible functions against the supplied documents, photos and a report within 3 business days. This is not a technical expert opinion, installation inspection or a replacement for handover by an authorised specialist.","from PLN 990 — final price before engagement"),("Corrective-work check","One visit up to 90 minutes, limited to items in my baseline report. New defects or wider scope require a separate quotation.","from PLN 590 — final price before engagement"),("Delivery support","Control of several agreed stages with a decision, risk and next-action log. Hours, visits and reporting are defined in the offer.","individual quotation")],
"products_b2b":[("Project status review","Current-state diagnosis, risks and open items, priorities and a 14- or 30-day action plan.","individual quotation"),("Stage control","One critical outcome: production, dispatch or installation readiness, stabilisation plan or close-out.","individual quotation"),("Stage or project PM","Plan, decision and risk logs, reporting, coordination of interfaces and formal close-out.","stage-based or percentage fee"),("Ongoing PM support","Agreed time blocks, outcomes and reporting rhythm — not unlimited availability.","monthly time package")],
"pricing_note":"Fees are agreed individually. If a percentage model is used, it applies only to the net value of packages I actually coordinate, not to the entire investment. The minimum fee, maximum cap, exclusions, additional costs and change rules are stated in the written offer.",
"b2c_terms":"B2C prices are final consumer prices. Travel within Konin is included; outside Konin it is PLN 2/km for the return distance, with parking and tolls subject to prior approval. Rescheduling or cancellation is free at least 24 hours in advance; later changes may incur 50% of the booked service price plus travel costs already incurred. Statutory consumer rights remain unchanged. The complete scope and final price are confirmed in writing before a contract is concluded."
},
"de": {
"home":"Start", "private":"Privatkunden", "business":"Für Unternehmen", "process":"Arbeitsweise", "proof":"Erfahrung und Unterlagen", "about":"Über mich", "contact":"Situation beschreiben", "privacy":"Datenschutz", "skip":"Zum Inhalt springen", "menu":"Menü", "footer":"Projektsteuerung für Maßmöbel und Fit-out · Konin · PL/EN/DE", "footnote":"Umfang und Verantwortungsgrenzen werden vor Beginn schriftlich vereinbart.",
"eyebrow":"PROJEKTSTEUERUNG / MASSMÖBEL / FIT-OUT", "hero":"Ruhigere Umsetzung. Klare Entscheidungen. Dokumentierte Abnahme.", "lead":"Ich steuere und kontrolliere die Umsetzung von Maßmöbeln und Fit-out für Privatkunden und Unternehmen. Ich strukturiere Umfang, Risiken, Entscheidungen, Qualität, Montage und Abnahme — ohne die Rolle von Planer oder Auftragnehmer zu übernehmen.", "b2c_cta":"Mein Möbelprojekt besprechen", "b2b_cta":"Unterstützung für mein Unternehmen", "two_paths":"Zwei Wege. Ein Kontrollstandard.", "private_lead":"Ich prüfe Angebote und Umfang, strukturiere Fragen an den Auftragnehmer und dokumentiere Montage, Abnahme und Nacharbeiten. Konin + 50 km; weitere Orte nach Vereinbarung.", "business_lead":"Ich verbinde Dokumentation, Produktion, Logistik, Baustellenbereitschaft, Montage und Abnahme zu einem kontrollierten Prozess. Unterstützung in PL/EN/DE.",
"proof_1":"Über 20 Jahre Praxis", "proof_1b":"in der Möbelbranche", "proof_2":"PL / EN / DE", "proof_2b":"internationale Koordination", "proof_3":"Produktion → Abnahme", "proof_3b":"Kontrolle entlang der Umsetzung", "proof_4":"Schriftliches Ergebnis", "proof_4b":"Bericht, Register oder Maßnahmenplan",
"entry":"Mit einem definierten Ergebnis beginnen.", "method":"Zuerst der Umfang. Dann die Kontrolle.", "steps":["Qualifikation und Eignung","Schriftliches Ergebnis, Umfang und Ausschlüsse","Kontrolle vereinbarter Punkte","Bericht, Entscheidungsregister oder Maßnahmenplan","Formaler Abschluss und Entscheidung über den nächsten Schritt"], "boundary_title":"Eine klare Rolle von Anfang an.", "boundary":"Ich plane keine Innenräume, führe keine Bauarbeiten aus und erbringe keine Rechts- oder Sachverständigenleistungen. Preise, Termine oder Qualität anderer Parteien werden nicht garantiert. Ich dokumentiere den Stand, benenne Risiken und kontrolliere nur den schriftlich vereinbarten Umfang. Für die sorgfältige Ausführung meines eigenen vereinbarten Umfangs bleibe ich verantwortlich; gesetzlich zwingende Haftung wird dadurch nicht ausgeschlossen.", "home_cta":"Beschreiben Sie die Situation — ich bestimme den passenden Einstieg.",
"private_title":"Unabhängige Kontrolle von Maßmöbeln — vor Bestellung, bei Montage und Abnahme.", "business_title":"Externer PM für Möbel- und Fit-out-Projekte — von der Risikodiagnose bis zum Phasenabschluss.", "services":"Leistungen", "screen_title":"Eignungsprüfung vor Unterlagen", "screen":"Zuerst kläre ich Bedarf, Umfang und erwartetes Ergebnis. Vor vertraulichen Unterlagen, einer Geheimhaltungsvereinbarung oder einem Angebot prüfe ich einen möglichen Interessenkonflikt. Unklare Punkte werden vor dem nächsten Schritt geklärt.", "conf_notice":"Für den ersten Kontakt genügt eine allgemeine Projektbeschreibung. Senden Sie vor der Eignungs- und Konfliktprüfung keine vertraulichen Unterlagen.",
"process_intro":"Jede Phase hat definierte Eingaben, ein Ergebnis, klare Grenzen und einen Abschlusszeitpunkt.", "process_steps":[("Qualifikation","Segment, Bedarf, Termin, Kapazität und Eignung."),("B2B-Eignungsprüfung","Interessenkonflikt und Vertraulichkeit vor Unterlagen."),("Schriftlicher Umfang","Ergebnis, Eingaben, Ausschlüsse, Grenzen, Preis und Termin."),("Kontrollierte Umsetzung","Nur vereinbarte Punkte; Änderungen erfordern schriftliche Zustimmung."),("Dokumentiertes Ergebnis","Bericht, Register, Bereitschaftsstatus oder Maßnahmenplan."),("Abschluss","Formale Übergabe und Entscheidung über eine weitere Phase.")],
"about_lead":"Über 20 Jahre Praxis in der Möbelbranche: Produktion, Teamführung, Qualität, Service und internationale Projektkoordination.", "about_h2":"Erfahrung von der Produktion bis zur Abnahme", "about_p1":"Meine Erfahrung reicht von produktions- und qualitätsnahen Aufgaben über Teamführung und Service bis zur internationalen Projektkoordination. Daher bewerte ich Unterlagen mit Blick auf Produktion, Logistik und Montage.", "about_p2":"Ich arbeite auf Polnisch, Englisch und Deutsch. Öffentlich zeige ich nur freigegebene Materialien; weitere Erfahrung beschreibe ich ohne Kundennamen oder vertrauliche Daten.", "about_role":"Ich ersetze weder Planer noch Auftragnehmer oder Sachverständige. Ich unterstütze Vorbereitung und Kontrolle der Umsetzung im vereinbarten Umfang.",
"contact_intro":"Wählen Sie einen Weg. Die erste Nachricht ist eine unverbindliche Anfrage — sie reserviert keinen Termin, begründet keinen Vertrag und bestätigt keine Projektannahme.", "email_alt":"Lieber kurz? Schreiben Sie direkt:", "availability_notice":"Derzeit nehme ich ausschließlich unverbindliche Anfragen an. Bis zum Abschluss der formalen Voraussetzungen schließe ich keine entgeltlichen Verträge, nehme keine Zahlungen an und reserviere keine Ausführungstermine.", "territory_note":"Kommunikation auf Polnisch, Englisch oder Deutsch bedeutet nicht automatisch, dass Leistungen im Ausland angeboten werden. Hauptleistungsgebiet ist Polen; jedes Auslandsprojekt erfordert eine vorherige rechtliche und steuerliche Klärung.", "form_b2c_title":"Beschreiben Sie Ihr Vorhaben", "form_b2b_title":"B2B-Projekt beschreiben", "optional":"optional", "send_b2c":"E-Mail vorbereiten", "send_b2b":"E-Mail vorbereiten", "service":"Gewählte Leistung", "select_service":"Diese Leistung wählen",
"products_b2c":[("Beratung vor Bestellung","Prüfung eines Angebots und der Unterlagen für einen Einbau, Gespräch bis 60 Minuten und schriftliche Liste von Lücken, Risiken und Fragen innerhalb von 2 Werktagen nach vollständigem Eingang.","590 PLN — Endpreis für Verbraucher"),("Begleitung bei der Abnahme und Bericht zum sichtbaren Umfang","Ein Termin bis 2 Stunden, ein Ort und ein Einbau; Prüfung sichtbarer Elemente und zugänglicher Funktionen anhand der übergebenen Unterlagen, Fotos und Bericht innerhalb von 3 Werktagen. Keine technische Begutachtung, Installationsprüfung oder Abnahme durch einen befugten Fachmann.","ab 990 PLN — Endpreis vor Beauftragung"),("Kontrolle der Nacharbeiten","Ein Termin bis 90 Minuten, ausschließlich Positionen aus meinem Ausgangsbericht. Neue Mängel oder ein größerer Umfang erfordern ein separates Angebot.","ab 590 PLN — Endpreis vor Beauftragung"),("Begleitung der Umsetzung","Kontrolle mehrerer vereinbarter Phasen mit Entscheidungs-, Risiko- und Maßnahmenliste. Stunden, Termine und Berichte werden im Angebot festgelegt.","individuelles Angebot")],
"products_b2b":[("Projektstatus prüfen","Statusdiagnose, Risiken und offene Punkte, Prioritäten sowie ein 14- oder 30-Tage-Maßnahmenplan.","individuelles Angebot"),("Phasenkontrolle","Ein kritisches Ergebnis: Produktions-, Versand- oder Montagebereitschaft, Maßnahmenplan oder Abschluss.","individuelles Angebot"),("PM für Phase oder Projekt","Plan, Entscheidungs- und Risikoregister, Status, Koordination der Schnittstellen und formaler Abschluss.","phasenbezogene oder prozentuale Vergütung"),("Laufende PM-Unterstützung","Vereinbarte Zeitblöcke, Ergebnisse und Berichtsintervalle — keine ständige Verfügbarkeit.","monatliches Zeitpaket")],
"pricing_note":"Die Vergütung wird individuell vereinbart. Bei einem Prozentmodell gilt ausschließlich der Nettowert der von mir tatsächlich koordinierten Leistungspakete, nicht die Gesamtinvestition. Mindesthonorar, Obergrenze, Ausschlüsse, Zusatzkosten und Änderungsregeln stehen im schriftlichen Angebot.",
"b2c_terms":"B2C-Preise sind Endpreise für Verbraucher. Anfahrt innerhalb von Konin ist enthalten; außerhalb von Konin werden 2 PLN/km für Hin- und Rückweg berechnet, Park- und Mautkosten nur nach vorheriger Zustimmung. Kostenfreie Änderung oder Absage ist mindestens 24 Stunden vorher möglich; danach können 50 % des gebuchten Leistungspreises und bereits entstandene Fahrtkosten berechnet werden. Gesetzliche Verbraucherrechte bleiben unberührt. Vollständiger Umfang und Endpreis werden vor Vertragsschluss schriftlich bestätigt."
}}

LABELS = {
"pl": {"name":"Imię", "email":"E-mail", "phone":"Telefon i preferowana pora kontaktu", "location":"Lokalizacja lub kod pocztowy", "stage":"Etap", "type":"Rodzaj zabudowy", "date":"Planowany termin", "message":"Opis sytuacji i oczekiwany rezultat", "source":"Skąd o mnie wiesz?", "company":"Firma", "role":"Rola", "project":"Typ projektu i aktualny etap", "critical":"Termin krytyczny", "outcome":"Oczekiwany rezultat", "parties":"Nazwy firm lub publicznie identyfikowalnych podmiotów albo ogólne kategorie stron", "language":"Preferowany język", "consent":"Zapoznałem/am się z polityką prywatności i zgadzam się na kontakt w sprawie zapytania.", "conf":"Potwierdzam, że zgłoszenie nie zawiera nieuzgodnionych informacji poufnych.", "fine_b2c":"Na tym etapie nie przyjmuję załączników. Wysłanie formularza nie rezerwuje terminu i nie oznacza przyjęcia zlecenia.", "fine_b2b":"Nie wpisuj danych osób fizycznych, danych kontaktowych, informacji poufnych ani treści objętych NDA. Zgłoszenie nie oznacza przyjęcia projektu ani zgody na przesłanie dokumentacji poufnej."},
"en": {"name":"Name", "email":"Email", "phone":"Phone and preferred contact time", "location":"Location or postal code", "stage":"Stage", "type":"Furniture or built-in type", "date":"Planned date", "message":"Situation and expected outcome", "source":"How did you find me?", "company":"Company", "role":"Role", "project":"Project type and current stage", "critical":"Critical date", "outcome":"Expected outcome", "parties":"Company or publicly identifiable entity names, or general party categories", "language":"Preferred language", "consent":"I have read the privacy policy and agree to be contacted about this enquiry.", "conf":"I confirm that this submission contains no unapproved confidential information.", "fine_b2c":"No attachments are accepted at this stage. Sending does not reserve a date or accept an order.", "fine_b2b":"Do not enter personal or contact data, confidential information or NDA-protected content. Submission does not accept the project or permit confidential documents to be sent."},
"de": {"name":"Name", "email":"E-Mail", "phone":"Telefon und bevorzugte Kontaktzeit", "location":"Ort oder Postleitzahl", "stage":"Phase", "type":"Art der Möbel oder Einbauten", "date":"Geplanter Termin", "message":"Situation und erwartetes Ergebnis", "source":"Wie haben Sie mich gefunden?", "company":"Unternehmen", "role":"Rolle", "project":"Projektart und aktuelle Phase", "critical":"Kritischer Termin", "outcome":"Erwartetes Ergebnis", "parties":"Namen von Unternehmen oder öffentlich identifizierbaren Organisationen beziehungsweise allgemeine Kategorien", "language":"Bevorzugte Sprache", "consent":"Ich habe die Datenschutzerklärung gelesen und stimme der Kontaktaufnahme zu dieser Anfrage zu.", "conf":"Ich bestätige, dass diese Anfrage keine nicht abgestimmten vertraulichen Informationen enthält.", "fine_b2c":"In dieser Phase werden keine Anhänge angenommen. Das Absenden reserviert keinen Termin und bestätigt keinen Auftrag.", "fine_b2b":"Keine personenbezogenen oder Kontaktdaten, vertraulichen Informationen oder NDA-Inhalte eingeben. Die Anfrage bedeutet weder Projektannahme noch Erlaubnis zum Senden vertraulicher Unterlagen."}
}

STAGES = {
"pl":["Przed zamówieniem","W realizacji","Montaż","Odbiór","Poprawki"],
"en":["Before ordering","In delivery","Installation","Handover","Corrective work"],
"de":["Vor Bestellung","In Umsetzung","Montage","Abnahme","Nacharbeiten"]}

def head(lang, title, desc, key):
    page_url = "https://adam-jakubowski.com" + url(key, lang)
    alternates = "".join(f'<link rel="alternate" hreflang="{l}" href="https://adam-jakubowski.com{url(key,l)}">' for l in LANGS)
    alternates += '<link rel="alternate" hreflang="x-default" href="https://adam-jakubowski.com/pl/">'
    full = f"{title} — Adam Jakubowski"
    og = "https://adam-jakubowski.com/assets/og/adam-jakubowski-project-delivery.jpg"
    robots = '<meta name="robots" content="noindex,follow">' if key == 'thanks' else ''
    return f'''<!doctype html><html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="{escape(desc)}">{robots}<meta name="theme-color" content="#0f100f"><title>{escape(full)}</title><link rel="icon" href="/assets/logo-aj.svg"><link rel="describedby" href="/llms.txt"><link rel="stylesheet" href="/site-v10.css?v=11"><script defer src="/site-v10.js?v=11"></script><link rel="canonical" href="{page_url}">{alternates}<meta property="og:type" content="website"><meta property="og:site_name" content="Adam Jakubowski — Project Delivery"><meta property="og:title" content="{escape(full)}"><meta property="og:description" content="{escape(desc)}"><meta property="og:url" content="{page_url}"><meta property="og:image" content="{og}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{escape(full)}"><meta name="twitter:description" content="{escape(desc)}"><meta name="twitter:image" content="{og}"></head><body><a class="skip" href="#main">{T[lang]['skip']}</a>'''

def nav(lang, key):
    c=T[lang]
    links=("private","business","process","proof","about")
    alts="".join(f'<a href="{url(key,l)}" lang="{l}" hreflang="{l}" aria-label="{l.upper()}">{l.upper()}</a>' for l in LANGS)
    return f'''<header class="topbar"><a class="brand" href="{url('home',lang)}"><img src="/assets/logo-aj.svg" alt="" width="44" height="44"><span><b>ADAM JAKUBOWSKI</b><small>PROJECT DELIVERY</small></span></a><button class="menu" aria-expanded="false" aria-controls="nav">{c['menu']}</button><nav id="nav">{''.join(f'<a href="{url(k,lang)}">{c[k]}</a>' for k in links)}<span class="langs">{alts}</span><a class="nav-cta" href="{url('contact',lang)}">{c['contact']}</a></nav></header>'''

def foot(lang):
    c=T[lang]
    return f'''<footer><div><b>Adam Jakubowski</b><p>{c['footer']}</p></div><div><a href="mailto:{EMAIL}">{EMAIL}</a><a href="{url('privacy',lang)}">{c['privacy']}</a><a href="{url('faq',lang)}">FAQ</a></div><p class="fine">{c['footnote']}</p></footer></body></html>'''

def layout(lang,title,desc,key,body):
    return head(lang,title,desc,key)+nav(lang,key)+f'<main id="main">{body}</main>'+foot(lang)

def cards(items, form_url=None, cta_label=None, availability_notice=None):
    def one(item):
        a,b,d=item
        cta=f'<a class="text-link service-cta" href="{form_url}?service={quote(a)}">{escape(cta_label)} →</a>' if form_url and cta_label else ''
        availability=f'<small class="availability">{escape(availability_notice)}</small>' if availability_notice else ''
        return f'<article class="card"><h3>{escape(a)}</h3><p>{escape(b)}</p><strong>{escape(d)}</strong>{availability}{cta}</article>'
    return '<div class="cards">'+''.join(one(item) for item in items)+'</div>'

def write(lang,key,title,desc,body):
    (ROOT/lang).mkdir(exist_ok=True)
    (ROOT/lang/filename(key,lang)).write_text(layout(lang,title,desc,key,body),encoding="utf-8")

for lang in LANGS:
    c=T[lang]; l=LABELS[lang]
    proof_items=((c['proof_1'],c['proof_1b']),(c['proof_2'],c['proof_2b']),(c['proof_3'],c['proof_3b']),(c['proof_4'],c['proof_4b']))
    proof_strip='<aside class="proof-strip" aria-label="'+c['proof']+'">'+''.join(f'<div><strong>{a}</strong><span>{b}</span></div>' for a,b in proof_items)+'</aside>'
    home=f'''<section class="hero-visual"><div class="hero-copy"><p class="eyebrow">{c['eyebrow']}</p><h1>{c['hero']}</h1><p class="lead">{c['lead']}</p><div class="dual-actions"><a class="button b2c" data-track="choose_b2c" href="{url('private',lang)}">{c['b2c_cta']}</a><a class="button secondary" data-track="choose_b2b" href="{url('business',lang)}">{c['b2b_cta']}</a></div><p class="notice">{c['availability_notice']}</p></div><figure><img src="/assets/projects/landbyska-verket/landbyska-verket-cover.webp" width="1600" height="1000" alt="Landbyska Verket"><figcaption>Landbyska Verket · {'doświadczenie zawodowe po stronie STOLPIN' if lang=='pl' else 'professional experience on the STOLPIN side' if lang=='en' else 'Berufserfahrung auf Seiten von STOLPIN'}</figcaption></figure></section>{proof_strip}
<section class="light"><div class="section-head"><p>01 / B2C + B2B</p><h2>{c['two_paths']}</h2></div><div class="split"><article><span>B2C</span><h3>{c['private']}</h3><p>{c['private_lead']}</p><a class="text-link" href="{url('private',lang)}">{c['b2c_cta']} →</a></article><article><span>B2B</span><h3>{c['business']}</h3><p>{c['business_lead']}</p><a class="text-link" href="{url('business',lang)}">{c['b2b_cta']} →</a></article></div></section>
<section class="dark"><div class="section-head"><p>02 / {'PUNKT STARTU' if lang=='pl' else 'ENTRY SERVICES' if lang=='en' else 'EINSTIEGSLEISTUNGEN'}</p><h2>{c['entry']}</h2></div>{cards([c['products_b2c'][0],c['products_b2c'][1],c['products_b2b'][0]],availability_notice=c['availability_notice'])}</section>
<section class="light"><div class="section-head"><p>03 / {c['process'].upper()}</p><h2>{c['method']}</h2></div><ol class="steps">{''.join(f'<li>{s}</li>' for s in c['steps'])}</ol><a class="text-link" href="{url('process',lang)}">{c['process']} →</a></section>
<section class="boundary"><h2>{c['boundary_title']}</h2><p>{c['boundary']}</p></section><section class="cta"><h2>{c['home_cta']}</h2><a class="button" href="{url('contact',lang)}">{c['contact']}</a></section>'''
    write(lang,'home',c['home'],c['lead'],home)

    private=f'''<header class="page-hero"><p class="eyebrow">B2C / KONIN + 50 KM</p><h1>{c['private_title']}</h1><p class="lead">{c['private_lead']}</p><a class="button" href="{url('b2c_form',lang)}">{c['b2c_cta']}</a></header><section class="light"><div class="section-head"><p>01 / {c['services'].upper()}</p><h2>{c['private']}</h2></div>{cards(c['products_b2c'],url('b2c_form',lang),c['select_service'],c['availability_notice'])}<p class="notice pricing-terms">{c['b2c_terms']}</p><p class="notice">{c['territory_note']}</p></section><section class="boundary"><h2>{c['boundary_title']}</h2><p>{c['boundary']}</p></section><section class="cta"><h2>{c['home_cta']}</h2><a class="button" href="{url('b2c_form',lang)}">{c['form_b2c_title']}</a></section>'''
    write(lang,'private',c['private'],c['private_lead'],private)

    business=f'''<header class="page-hero"><p class="eyebrow">B2B / PL · EN · DE</p><h1>{c['business_title']}</h1><p class="lead">{c['business_lead']}</p><p class="notice">{c['conf_notice']}</p><a class="button" href="{url('b2b_form',lang)}">{c['form_b2b_title']}</a></header><section class="light"><div class="section-head"><p>01 / {c['services'].upper()}</p><h2>{c['business']}</h2></div>{cards(c['products_b2b'],url('b2b_form',lang),c['select_service'])}<p class="notice">{c['pricing_note']}</p><p class="notice">{c['availability_notice']} {c['territory_note']}</p></section><section class="dark"><h2>{c['screen_title']}</h2><p class="lead">{c['screen']}</p></section><section class="boundary"><h2>{c['boundary_title']}</h2><p>{c['boundary']}</p></section><section class="cta"><h2>{c['business_title']}</h2><a class="button" href="{url('b2b_form',lang)}">{c['form_b2b_title']}</a></section>'''
    write(lang,'business',c['business'],c['business_lead'],business)

    detailed=''.join(f'<li><b>{a}</b><span>{b}</span></li>' for a,b in c['process_steps'])
    process=f'''<header class="page-hero compact"><p class="eyebrow">{c['process'].upper()}</p><h1>{c['process']}</h1><p class="lead">{c['process_intro']}</p></header><section class="light"><ol class="steps detailed">{detailed}</ol></section><section class="boundary"><p>{c['boundary']}</p></section><section class="cta"><h2>{c['home_cta']}</h2><a class="button" href="{url('contact',lang)}">{c['contact']}</a></section>'''
    write(lang,'process',c['process'],c['process_intro'],process)

    evidence_labels={"pl":("Doświadczenie i przykładowe rezultaty","Przykładowy raport odbioru","Checklista przed zaliczką","Rejestr ryzyk i decyzji","Udokumentowane doświadczenie zawodowe","Zobacz case study"),"en":("Experience and sample outcomes","Sample handover report","Pre-order checklist","Risk and decision register","Documented professional experience","View case study"),"de":("Erfahrung und Beispielergebnisse","Beispiel-Abnahmebericht","Checkliste vor Anzahlung","Risiko- und Entscheidungsregister","Dokumentierte Berufserfahrung","Fallstudie ansehen")}[lang]
    proof=f'''<header class="page-hero compact"><p class="eyebrow">{c['proof'].upper()}</p><h1>{evidence_labels[0]}</h1></header><section class="light"><div class="cards"><article class="card"><h3>{evidence_labels[1]}</h3><a class="text-link" href="{url('sample_report',lang)}">→</a></article><article class="card"><h3>{evidence_labels[2]}</h3><a class="text-link" href="{url('checklist',lang)}">→</a></article><article class="card"><h3>{evidence_labels[3]}</h3><a class="text-link" href="{url('risk_register',lang)}">→</a></article></div></section><section class="case-feature"><img src="/assets/projects/landbyska-verket/landbyska-verket-cover.webp" width="1600" height="1000" alt="Landbyska Verket"><div><p class="eyebrow">{evidence_labels[4].upper()}</p><h2>Landbyska Verket, Stockholm</h2><p>{'Lead Project Manager po stronie wykonawcy zabudowy meblowej — firmy STOLPIN. Materiał nie sugeruje autorstwa całego wnętrza ani niezależnej realizacji.' if lang=='pl' else 'Lead Project Manager on the custom furniture contractor side — STOLPIN. This material does not claim authorship of the whole interior or an independent commission.' if lang=='en' else 'Lead Project Manager auf Seiten des Möbelbau-Auftragnehmers STOLPIN. Das Material beansprucht weder die Urheberschaft des gesamten Interieurs noch einen unabhängigen Auftrag.'}</p><a class="text-link" href="/{lang}/landbyska-verket">{evidence_labels[5]} →</a></div></section>'''
    write(lang,'proof',c['proof'],c['proof_1']+' — '+c['proof_1b'],proof)

    about=f'''<header class="page-hero compact"><p class="eyebrow">ADAM JAKUBOWSKI</p><h1>{c['about']}</h1><p class="lead">{c['about_lead']}</p></header><section class="about-grid light"><figure><img src="/assets/adam-jakubowski-portrait-v2.jpg" width="1254" height="1254" alt="Adam Jakubowski"></figure><div><h2>{c['about_h2']}</h2><p>{c['about_p1']}</p><p>{c['about_p2']}</p><p class="notice">{c['about_role']}</p><p class="language-badge">PL / EN / DE</p></div></section><section class="cta"><h2>{c['home_cta']}</h2><a class="button" href="{url('contact',lang)}">{c['contact']}</a></section>'''
    write(lang,'about',c['about'],c['about_lead'],about)

    contact=f'''<header class="page-hero compact"><p class="eyebrow">{'KONTAKT' if lang=='pl' else 'CONTACT' if lang=='en' else 'KONTAKT'}</p><h1>{c['contact']}</h1><p class="lead">{c['contact_intro']}</p><p class="notice">{c['availability_notice']} {c['territory_note']}</p></header><section class="light"><div class="split"><article><span>B2C</span><h2>{c['private']}</h2><p>{c['private_lead']}</p><a class="button" data-track="form_b2c_open" href="{url('b2c_form',lang)}">{c['b2c_cta']}</a></article><article><span>B2B</span><h2>{c['business']}</h2><p>{c['business_lead']}</p><a class="button" data-track="form_b2b_open" href="{url('b2b_form',lang)}">{c['b2b_cta']}</a></article></div><p class="email-line">{c['email_alt']} <a href="mailto:{EMAIL}">{EMAIL}</a></p></section>'''
    write(lang,'contact',c['contact'],c['contact_intro'],contact)

    star=' <span aria-hidden="true">*</span>'
    opt=f' <span class="optional">({c["optional"]})</span>'
    options=''.join(f'<option>{x}</option>' for x in STAGES[lang])
    b2c_services=''.join(f'<option value="{escape(x[0])}">{escape(x[0])}</option>' for x in c['products_b2c'])
    b2b_services=''.join(f'<option value="{escape(x[0])}">{escape(x[0])}</option>' for x in c['products_b2b'])
    email_box=f'''<aside class="email-option"><span>{c['email_alt']}</span><a href="mailto:{EMAIL}">{EMAIL}</a></aside>'''
    mail_note={"pl":"Pola pozostają w przeglądarce. Przycisk przygotuje wiadomość w Twoim programie pocztowym; dane zostaną wysłane dopiero po Twoim potwierdzeniu. Nie dodawaj danych wrażliwych, poufnych dokumentów ani załączników na pierwszym etapie.","en":"The fields remain in your browser. The button prepares a message in your email application; data are sent only after you confirm. Do not add sensitive data, confidential documents or attachments at this stage.","de":"Die Felder bleiben im Browser. Die Schaltfläche erstellt eine Nachricht in Ihrem E-Mail-Programm; Daten werden erst nach Ihrer Bestätigung gesendet. Fügen Sie in dieser Phase keine sensiblen Daten, vertraulichen Unterlagen oder Anhänge hinzu."}[lang]
    privacy_note={"pl":"Zasady przetwarzania wiadomości e-mail opisuje","en":"Email processing is described in the","de":"Die Verarbeitung von E-Mails ist beschrieben in der"}[lang]
    b2c=f'''<header class="page-hero compact"><p class="eyebrow">B2C</p><h1>{c['form_b2c_title']}</h1><p class="lead">{c['private_lead']}</p><p class="notice">{c['availability_notice']}</p></header><section class="form-section">{email_box}<form class="lead-form" action="mailto:{EMAIL}" method="GET" data-mailto-form data-segment="B2C" data-subject="B2C website enquiry"><input type="hidden" name="segment" value="B2C"><label>{c['service']}{star}<select name="service" required><option value="">—</option>{b2c_services}</select></label><label>{l['name']}{star}<input name="name" autocomplete="name" required></label><label>{l['email']}{star}<input type="email" name="email" autocomplete="email" required></label><label>{l['phone']}{opt}<input name="phone" autocomplete="tel"></label><label>{l['location']}{star}<input name="location" required></label><label>{l['stage']}{star}<select name="stage" required><option value="">—</option>{options}</select></label><label>{l['type']}{opt}<input name="scope_type"></label><label>{l['date']}{opt}<input name="planned_date"></label><label>{l['message']}{star}<textarea name="message" rows="7" required></textarea></label><label>{l['source']}{opt}<input name="source"></label><p class="fine">{mail_note} {privacy_note} <a href="{url('privacy',lang)}">{c['privacy']}</a>. {l['fine_b2c']}</p><button class="button" type="submit">{c['send_b2c']}</button><p class="form-status" role="status" aria-live="polite"></p></form></section>'''
    write(lang,'b2c_form',c['form_b2c_title'],c['private_lead'],b2c)

    b2b=f'''<header class="page-hero compact"><p class="eyebrow">B2B / {'PIERWSZY KONTAKT' if lang=='pl' else 'INITIAL ENQUIRY' if lang=='en' else 'ERSTE ANFRAGE'}</p><h1>{c['form_b2b_title']}</h1><p class="notice"><strong>{c['availability_notice']}</strong><br>{c['conf_notice']}</p></header><section class="form-section">{email_box}<form class="lead-form" action="mailto:{EMAIL}" method="GET" data-mailto-form data-segment="B2B" data-subject="B2B website enquiry"><input type="hidden" name="segment" value="B2B"><label>{c['service']}{star}<select name="service" required><option value="">—</option>{b2b_services}</select></label><label>{l['name']}{star}<input name="name" autocomplete="name" required></label><label>{l['company']}{star}<input name="company" autocomplete="organization" required></label><label>{l['role']}{opt}<input name="role"></label><label>{l['email']}{star}<input type="email" name="email" autocomplete="email" required></label><label>{l['location']}{star}<input name="location" required></label><label>{l['project']}{star}<input name="project_stage" required></label><label>{l['critical']}{opt}<input name="critical_date"></label><label>{l['outcome']}{star}<textarea name="expected_outcome" rows="5" required></textarea></label><label>{l['parties']}{opt}<textarea name="screening_parties" rows="3"></textarea></label><label>{l['language']}{star}<select name="language" required><option>PL</option><option>EN</option><option>DE</option></select></label><label>{l['source']}{opt}<input name="source"></label><label class="check"><input type="checkbox" name="confidentiality_ack" required><span>{l['conf']}</span></label><p class="fine">{mail_note} {privacy_note} <a href="{url('privacy',lang)}">{c['privacy']}</a>. {l['fine_b2b']}</p><button class="button" type="submit">{c['send_b2b']}</button><p class="form-status" role="status" aria-live="polite"></p></form></section>'''
    write(lang,'b2b_form',c['form_b2b_title'],c['business_lead'],b2b)

    privacy_text={
    "pl":("Administrator i kontakt","Administratorem danych jest Adam Jakubowski, Konin, Polska. Kontakt: info@adam-jakubowski.com.","Jak działa strona","Strona jest hostowana i zabezpieczana przez Cloudflare Pages. Nie używa kont reklamowych, narzędzi analitycznych ani opcjonalnych plików cookie. Pola na stronach kontaktowych pozostają lokalnie w przeglądarce i jedynie przygotowują wiadomość w programie pocztowym użytkownika. Strona nie przekazuje treści zapytań do zewnętrznego operatora formularzy.","Cele i podstawy","Dane dobrowolnie przesłane e-mailem są używane do odpowiedzi, oceny dopasowania i dostępności, sprawdzenia możliwego konfliktu interesów oraz działań na żądanie przed ewentualną umową — art. 6 ust. 1 lit. b RODO. Niezbędne zapisy korespondencji, bezpieczeństwo i ochrona roszczeń mogą opierać się na prawnie uzasadnionym interesie — art. 6 ust. 1 lit. f RODO; obowiązki prawne na art. 6 ust. 1 lit. c RODO. Podanie danych jest dobrowolne, lecz bez danych kontaktowych i opisu sprawy odpowiedź może być niemożliwa.","Odbiorcy i transfery","Dane mogą być przetwarzane przez dostawcę poczty i niezbędne usługi IT. Cloudflare może przetwarzać techniczne dane połączenia, takie jak adres IP, na potrzeby dostarczenia i ochrony strony. Dostawcy mogą przetwarzać dane poza EOG z zastosowaniem mechanizmów wymaganych przez RODO, w tym standardowych klauzul umownych. Dane nie są sprzedawane.","Retencja","Zapytania, które nie prowadzą do współpracy, są usuwane co do zasady po 6 miesiącach. Korespondencja dotycząca prowadzonej sprawy jest przechowywana do 12 miesięcy po jej zamknięciu, a dokumenty związane z umową lub obowiązkami prawnymi przez okres wymagany prawem albo niezbędny do ochrony roszczeń. Techniczne logi Cloudflare podlegają okresom retencji tego dostawcy.","Prawa","Możesz żądać dostępu, sprostowania, usunięcia, ograniczenia lub przeniesienia danych oraz wnieść sprzeciw. Jeżeli podstawą jest zgoda, możesz ją wycofać. Masz prawo złożyć skargę do Prezesa UODO. Nie stosuję zautomatyzowanego podejmowania decyzji ani profilowania.","Ostatnia aktualizacja","4 października 2026 r."),
    "en":("Controller and contact","The data controller is Adam Jakubowski, Konin, Poland. Contact: info@adam-jakubowski.com.","How the site works","The site is hosted and protected by Cloudflare Pages. It uses no advertising accounts, analytics tools or optional cookies. Fields on the contact pages remain locally in the browser and only prepare a message in the user’s email application. The site does not transmit enquiry content to an external form operator.","Purposes and legal bases","Data voluntarily sent by email are used to respond, assess fit and capacity, check a potential conflict of interest and take requested steps before a possible contract under Article 6(1)(b) GDPR. Necessary correspondence records, security and legal-claim protection may rely on legitimate interests under Article 6(1)(f); legal obligations on Article 6(1)(c). Providing data is voluntary, but without contact details and a description of the matter a response may be impossible.","Recipients and transfers","Data may be processed by the email provider and necessary IT services. Cloudflare may process technical connection data such as IP addresses to deliver and protect the site. Providers may process data outside the EEA using mechanisms required by the GDPR, including Standard Contractual Clauses. Data are not sold.","Retention","Enquiries that do not lead to cooperation are generally removed after 6 months. Correspondence concerning an active matter is kept for up to 12 months after closure; contract or legally required records are retained for the period required by law or needed to protect claims. Cloudflare technical logs follow that provider’s retention periods.","Rights","You may request access, rectification, erasure, restriction or portability and object to processing. Where consent is the basis, it may be withdrawn. You may complain to the Polish data protection authority. I do not use automated decision-making or profiling.","Last updated","4 October 2026."),
    "de":("Verantwortlicher und Kontakt","Verantwortlicher ist Adam Jakubowski, Konin, Polen. Kontakt: info@adam-jakubowski.com.","Funktionsweise der Website","Die Website wird über Cloudflare Pages bereitgestellt und geschützt. Sie verwendet keine Werbekonten, Analysewerkzeuge oder optionalen Cookies. Felder auf den Kontaktseiten bleiben lokal im Browser und erstellen nur eine Nachricht im E-Mail-Programm des Nutzers. Die Website übermittelt Anfragen nicht an einen externen Formulardienst.","Zwecke und Rechtsgrundlagen","Freiwillig per E-Mail übermittelte Daten dienen der Beantwortung, der Prüfung von Eignung und Kapazität, möglicher Interessenkonflikte sowie angeforderter vorvertraglicher Schritte gemäß Art. 6 Abs. 1 lit. b DSGVO. Notwendige Korrespondenznachweise, Sicherheit und Anspruchsabwehr können auf berechtigten Interessen gemäß Art. 6 Abs. 1 lit. f, gesetzliche Pflichten auf Art. 6 Abs. 1 lit. c beruhen. Die Angabe von Daten ist freiwillig; ohne Kontaktdaten und eine Beschreibung kann eine Antwort jedoch unmöglich sein.","Empfänger und Übermittlungen","Daten können durch den E-Mail-Anbieter und notwendige IT-Dienste verarbeitet werden. Cloudflare kann technische Verbindungsdaten wie IP-Adressen zur Bereitstellung und zum Schutz der Website verarbeiten. Anbieter können Daten außerhalb des EWR auf Grundlage der von der DSGVO verlangten Mechanismen verarbeiten, darunter Standardvertragsklauseln. Daten werden nicht verkauft.","Speicherung","Anfragen ohne Zusammenarbeit werden grundsätzlich nach 6 Monaten gelöscht. Korrespondenz zu laufenden Vorgängen wird bis zu 12 Monate nach Abschluss gespeichert; Vertragsunterlagen oder gesetzlich erforderliche Aufzeichnungen so lange, wie es das Recht oder die Anspruchssicherung verlangt. Für technische Cloudflare-Protokolle gelten die Speicherfristen des Anbieters.","Rechte","Sie können Auskunft, Berichtigung, Löschung, Einschränkung oder Übertragbarkeit verlangen und Widerspruch einlegen. Eine erteilte Einwilligung kann widerrufen werden. Sie können sich bei der polnischen Datenschutzbehörde beschweren. Es gibt keine automatisierten Entscheidungen und kein Profiling.","Letzte Aktualisierung","4. Oktober 2026.")}[lang]
    privacy=''.join(f'<h2>{privacy_text[i]}</h2><p>{privacy_text[i+1]}</p>' for i in range(0,len(privacy_text),2))
    write(lang,'privacy',c['privacy'],c['privacy'],f'<header class="page-hero compact"><p class="eyebrow">{c["privacy"].upper()}</p><h1>{c["privacy"]}</h1></header><article class="legal light">{privacy}</article>')

    faq_items={"pl":[("Czy projektujesz meble lub wnętrza?","Nie. Analizuję i kontroluję uzgodniony zakres realizacji; nie zastępuję projektanta ani wykonawcy."),("Czy gwarantujesz koszt, termin lub jakość?","Nie. Dokumentuję stan, ryzyka i decyzje, ale nie gwarantuję wyników zależnych od innych stron."),("Czy mogę przesłać poufne dokumenty B2B?","Nie przed screeningiem dopasowania i konfliktu. Pierwszy formularz nie przyjmuje załączników.")],"en":[("Do you design furniture or interiors?","No. I review and control an agreed delivery scope; I do not replace the designer or contractor."),("Do you guarantee cost, timing or quality?","No. I document status, risks and decisions but do not guarantee outcomes controlled by other parties."),("Can I send confidential B2B documents?","Not before fit and conflict screening. The initial form does not accept attachments.")],"de":[("Planen Sie Möbel oder Innenräume?","Nein. Ich prüfe und kontrolliere den vereinbarten Umsetzungsumfang; ich ersetze weder Planer noch Auftragnehmer."),("Garantieren Sie Kosten, Termin oder Qualität?","Nein. Ich dokumentiere Stand, Risiken und Entscheidungen, garantiere aber keine Ergebnisse anderer Parteien."),("Kann ich vertrauliche B2B-Unterlagen senden?","Nicht vor der Eignungs- und Konfliktprüfung. Das erste Formular nimmt keine Anhänge an.")]}[lang]
    faq='<header class="page-hero compact"><p class="eyebrow">FAQ</p><h1>FAQ</h1></header><section class="faq light">'+''.join(f'<details><summary>{a}</summary><p>{b}</p></details>' for a,b in faq_items)+'</section>'
    write(lang,'faq','FAQ','FAQ',faq)

    samples={
    "pl":{
      "sample_report":("Przykładowy raport odbioru","Anonimowy przykład rezultatu usługi.",'''<header class="page-hero compact"><p class="eyebrow">PRZYKŁAD / ANONIMOWY</p><h1>Przykładowy raport odbioru</h1><p class="lead">Format poglądowy — nie jest raportem z projektu klienta.</p></header><article class="legal light"><h2>Zakres</h2><p>Jedna zabudowa kuchenna; elementy widoczne i dostępne funkcje porównane z rysunkiem rewizja 03 i uzgodnioną specyfikacją wykończeń.</p><h2>Pozycja 01 — ustawienie frontów</h2><p><strong>Klasyfikacja:</strong> stwierdzona niezgodność. <strong>Podstawa:</strong> rysunek 03, elewacja B. <strong>Dowód:</strong> widoczna różnica linii górnej. <strong>Status:</strong> otwarte. <strong>Działanie:</strong> regulacja i zdjęcie potwierdzające.</p><h2>Pozycja 02 — podłączenie urządzenia</h2><p><strong>Klasyfikacja:</strong> niesprawdzone. Urządzenie nie było podłączone. Weryfikacja wymaga uprawnionego specjalisty.</p><h2>Zamknięcie</h2><p>12 pozycji zamkniętych, 2 otwarte, 1 niesprawdzona. Ponowna wizyta jest osobną usługą.</p></article>'''),
      "checklist":("Checklista przed zaliczką","Praktyczna checklista przed zamówieniem.",'''<header class="page-hero compact"><p class="eyebrow">CHECKLISTA</p><h1>Przed wpłatą zaliczki</h1></header><article class="legal light"><h2>Zakres i dokumenty</h2><p>☐ Dokładna lista mebli i elementów<br>☐ Aktualna rewizja rysunków i wymiary<br>☐ Materiały, dekory, obrzeża, okucia i urządzenia<br>☐ Elementy wyłączone z oferty</p><h2>Odpowiedzialność</h2><p>☐ Kto mierzy i zatwierdza wymiary<br>☐ Kto przygotowuje instalacje i miejsce montażu<br>☐ Kto koordynuje inne branże<br>☐ Kto akceptuje zmiany i dodatkowe koszty</p><h2>Termin i odbiór</h2><p>☐ Daty produkcji, dostawy i montażu<br>☐ Warunki zmiany terminu<br>☐ Sposób odbioru i lista usterek<br>☐ Gwarancja, serwis i tryb reklamacji</p></article>'''),
      "risk_register":("Przykładowy rejestr ryzyk","Anonimowy przykład rezultatu usługi.",'''<header class="page-hero compact"><p class="eyebrow">PRZYKŁAD / ANONIMOWY</p><h1>Rejestr ryzyk i decyzji</h1></header><article class="legal light"><h2>R-01 — brak akceptacji wykończenia</h2><p><strong>Wpływ:</strong> blokada uruchomienia produkcji. <strong>Właściciel:</strong> osoba decyzyjna klienta. <strong>Status:</strong> otwarte. <strong>Decyzja:</strong> wybór próbki A lub B.</p><h2>R-02 — miejsce niegotowe</h2><p><strong>Wpływ:</strong> brak możliwości bezpiecznego rozpoczęcia montażu. <strong>Właściciel:</strong> generalny wykonawca. <strong>Dowód:</strong> checklista gotowości. <strong>Status:</strong> warunkowe.</p><h2>D-01 — bramka wysyłkowa</h2><p><strong>Decyzja:</strong> warunkowa zgoda po zamknięciu R-01 i pisemnym potwierdzeniu dostępu. <strong>Zatwierdza:</strong> wskazana osoba decyzyjna klienta.</p></article>''')},
    "en":{
      "sample_report":("Sample handover report","Anonymous example of a service deliverable.",'''<header class="page-hero compact"><p class="eyebrow">SAMPLE / ANONYMOUS</p><h1>Sample handover report</h1><p class="lead">Illustrative format only — not a report from a client project.</p></header><article class="legal light"><h2>Scope</h2><p>One fitted kitchen; visible elements and available functions compared with drawing revision 03 and the agreed finish schedule.</p><h2>Finding 01 — door alignment</h2><p><strong>Classification:</strong> observed non-conformity. <strong>Reference:</strong> drawing 03, elevation B. <strong>Evidence:</strong> visible difference in the upper edge line. <strong>Status:</strong> open. <strong>Next action:</strong> adjustment and completion photo.</p><h2>Finding 02 — electrical connection</h2><p><strong>Classification:</strong> not inspected. The appliance was not connected during the visit. Verification requires an authorised specialist.</p><h2>Closure</h2><p>12 points closed, 2 open, 1 not inspected. A follow-up visit is a separate service.</p></article>'''),
      "checklist":("Pre-order checklist","Practical checklist before placing an order.",'''<header class="page-hero compact"><p class="eyebrow">CHECKLIST</p><h1>Before paying a deposit</h1></header><article class="legal light"><h2>Scope and documents</h2><p>☐ Exact list of furniture and elements<br>☐ Latest drawing revision and dimensions<br>☐ Material, decor, edge, hardware and appliance specification<br>☐ Items excluded from the offer</p><h2>Responsibilities</h2><p>☐ Who measures and approves dimensions<br>☐ Who prepares utilities and the installation site<br>☐ Who coordinates other trades<br>☐ Who approves changes and additional cost</p><h2>Timing and handover</h2><p>☐ Production, delivery and installation dates<br>☐ Conditions that move the deadline<br>☐ Handover method and defect list<br>☐ Warranty, service and complaint route</p></article>'''),
      "risk_register":("Sample risk register","Anonymous example of a service deliverable.",'''<header class="page-hero compact"><p class="eyebrow">SAMPLE / ANONYMOUS</p><h1>Risk and decision register</h1></header><article class="legal light"><h2>R-01 — finish approval missing</h2><p><strong>Impact:</strong> production start blocked. <strong>Owner:</strong> client decision-maker. <strong>Status:</strong> open. <strong>Decision:</strong> approve sample A or B.</p><h2>R-02 — site not ready</h2><p><strong>Impact:</strong> installation cannot start safely. <strong>Owner:</strong> main contractor. <strong>Evidence:</strong> readiness checklist. <strong>Status:</strong> conditional.</p><h2>D-01 — dispatch gate</h2><p><strong>Decision:</strong> conditional go after closure of R-01 and written confirmation of access. <strong>Approved by:</strong> named client decision-maker.</p></article>''')},
    "de":{
      "sample_report":("Beispiel-Abnahmebericht","Anonymes Beispiel eines Leistungsergebnisses.",'''<header class="page-hero compact"><p class="eyebrow">BEISPIEL / ANONYM</p><h1>Beispiel-Abnahmebericht</h1><p class="lead">Nur ein Musterformat — kein Bericht aus einem Kundenprojekt.</p></header><article class="legal light"><h2>Umfang</h2><p>Eine Einbauküche; sichtbare Elemente und verfügbare Funktionen wurden mit Zeichnungsrevision 03 und der vereinbarten Oberflächenspezifikation verglichen.</p><h2>Punkt 01 — Ausrichtung der Fronten</h2><p><strong>Klassifizierung:</strong> festgestellte Abweichung. <strong>Grundlage:</strong> Zeichnung 03, Ansicht B. <strong>Nachweis:</strong> sichtbarer Versatz der Oberkante. <strong>Status:</strong> offen. <strong>Nächster Schritt:</strong> Justierung und Bestätigungsfoto.</p><h2>Punkt 02 — Geräteanschluss</h2><p><strong>Klassifizierung:</strong> nicht geprüft. Das Gerät war nicht angeschlossen. Die Prüfung erfordert eine autorisierte Fachkraft.</p><h2>Abschluss</h2><p>12 Punkte geschlossen, 2 offen, 1 nicht geprüft. Ein Folgetermin ist eine separate Leistung.</p></article>'''),
      "checklist":("Checkliste vor Anzahlung","Praktische Checkliste vor der Bestellung.",'''<header class="page-hero compact"><p class="eyebrow">CHECKLISTE</p><h1>Vor Zahlung der Anzahlung</h1></header><article class="legal light"><h2>Umfang und Unterlagen</h2><p>☐ Genaue Liste der Möbel und Elemente<br>☐ Aktuelle Zeichnungsrevision und Maße<br>☐ Spezifikation von Materialien, Dekoren, Kanten, Beschlägen und Geräten<br>☐ Von der Leistung ausgeschlossene Positionen</p><h2>Verantwortlichkeiten</h2><p>☐ Wer misst und Maße freigibt<br>☐ Wer Anschlüsse und Montageort vorbereitet<br>☐ Wer andere Gewerke koordiniert<br>☐ Wer Änderungen und Mehrkosten freigibt</p><h2>Termin und Abnahme</h2><p>☐ Termine für Produktion, Lieferung und Montage<br>☐ Bedingungen für Terminänderungen<br>☐ Abnahmeverfahren und Mängelliste<br>☐ Garantie, Service und Reklamationsweg</p></article>'''),
      "risk_register":("Beispiel-Risikoregister","Anonymes Beispiel eines Leistungsergebnisses.",'''<header class="page-hero compact"><p class="eyebrow">BEISPIEL / ANONYM</p><h1>Risiko- und Entscheidungsregister</h1></header><article class="legal light"><h2>R-01 — Oberflächenfreigabe fehlt</h2><p><strong>Auswirkung:</strong> Produktionsstart blockiert. <strong>Verantwortlich:</strong> benannte Entscheidungsperson des Kunden. <strong>Status:</strong> offen. <strong>Entscheidung:</strong> Muster A oder B freigeben.</p><h2>R-02 — Montageort nicht bereit</h2><p><strong>Auswirkung:</strong> sichere Montage nicht möglich. <strong>Verantwortlich:</strong> Generalunternehmer. <strong>Nachweis:</strong> Bereitschaftscheckliste. <strong>Status:</strong> bedingt.</p><h2>D-01 — Versandfreigabe</h2><p><strong>Entscheidung:</strong> bedingte Freigabe nach Abschluss von R-01 und schriftlicher Zugangsbestätigung. <strong>Freigabe durch:</strong> benannte Entscheidungsperson des Kunden.</p></article>''')}
    }[lang]
    for sample_key,(sample_title,sample_desc,sample_body) in samples.items():
        write(lang,sample_key,sample_title,sample_desc,sample_body)

    thanks_title={"pl":"Wiadomość jest gotowa do wysłania.","en":"Your message is ready to send.","de":"Ihre Nachricht ist zum Senden bereit."}[lang]
    thanks_lead={"pl":"Wyślij ją w swoim programie pocztowym. Samo przygotowanie wiadomości nie rezerwuje terminu ani nie oznacza przyjęcia zlecenia.","en":"Send it from your email application. Preparing the message does not reserve capacity or confirm project acceptance.","de":"Senden Sie sie in Ihrem E-Mail-Programm. Das Erstellen der Nachricht reserviert keinen Termin und bestätigt keine Projektannahme."}[lang]
    write(lang,'thanks',thanks_title,thanks_lead,f'<section class="simple-hero"><p class="eyebrow">✓</p><h1>{thanks_title}</h1><p class="lead">{thanks_lead}</p><a class="button" href="{url("home",lang)}">{c["home"]}</a></section>')

# Root Polish home and compatibility redirects.
root=(ROOT/'pl/index.html').read_text(encoding='utf-8').replace('href="/pl/"','href="/"',1).replace('https://adam-jakubowski.com/pl/','https://adam-jakubowski.com/')
(ROOT/'index.html').write_text(root,encoding='utf-8')
redirects={
'kontakt.html':'/pl/kontakt','zakres.html':'/pl/dla-klienta-prywatnego','proces.html':'/pl/proces','projekty.html':'/pl/dowody','o-mnie.html':'/pl/o-mnie'}
for old,target in redirects.items():
    (ROOT/old).write_text(f'<!doctype html><html lang="pl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta http-equiv="refresh" content="0;url={target}"><link rel="canonical" href="https://adam-jakubowski.com{target}"><title>Przekierowanie</title></head><body><a href="{target}">Przejdź dalej</a></body></html>',encoding='utf-8')
for lang in LANGS:
    localized={"zakres.html":filename('private',lang),"projekty.html":filename('proof',lang)}
    if lang=='en': localized.update({'o-mnie.html':'about.html','proces.html':'process.html','kontakt.html':'contact.html'})
    if lang=='de': localized.update({'o-mnie.html':'ueber-mich.html','proces.html':'arbeitsweise.html'})
    for old,new in localized.items():
        target=f'/{lang}/{new.removesuffix(".html")}'
        (ROOT/lang/old).write_text(f'<!doctype html><html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta http-equiv="refresh" content="0;url={target}"><link rel="canonical" href="https://adam-jakubowski.com{target}"><title>Redirect</title></head><body><a href="{target}">Continue</a></body></html>',encoding='utf-8')
urls=[]
for lang in LANGS:
    urls += ['https://adam-jakubowski.com'+url(key,lang) for key in PATHS if key != 'thanks']
    urls += [f'https://adam-jakubowski.com/{lang}/landbyska-verket']
(ROOT/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: https://adam-jakubowski.com/sitemap.xml\n',encoding='utf-8')
(ROOT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>{u}</loc></url>' for u in urls)+'</urlset>',encoding='utf-8')
(ROOT/'_headers').write_text("""/*
  Content-Security-Policy: default-src 'self'; img-src 'self' https: data:; style-src 'self'; script-src 'self'; connect-src 'self'; base-uri 'self'; form-action 'self' mailto:; frame-ancestors 'none'; upgrade-insecure-requests
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=()
""",encoding='utf-8')
clean_redirects=['/ /pl/ 301']
for lang in LANGS:
    clean_redirects.append(f'/{lang}/index.html /{lang}/ 301')
    clean_redirects += [f'/{lang}/{filename(key,lang)} {url(key,lang)} 301' for key in PATHS if key != 'home']
    clean_redirects.append(f'/{lang}/landbyska-verket.html /{lang}/landbyska-verket 301')
(ROOT/'_redirects').write_text('\n'.join(clean_redirects)+'\n',encoding='utf-8')
print(f"v11 generated: {len(urls)} sitemap URLs")
