import build_v9
from build_v9 import ROOT, layout, url, langs, extra
lang='pl'; c=langs[lang]; e=extra[lang]

process='''<header class="page-hero"><p class="eyebrow">METODA</p><h1>Jak pracuję</h1></header><section><ol class="steps detailed"><li><b>Kwalifikacja</b><span>Segment, potrzeba, termin, dostępność i dopasowanie.</span></li><li><b>Screening B2B</b><span>Konflikt interesów i poufność przed przyjęciem dokumentów.</span></li><li><b>Pisemny zakres</b><span>Rezultat, materiały wejściowe, wyłączenia, limity, cena i termin.</span></li><li><b>Kontrolowana realizacja</b><span>Wyłącznie uzgodnione punkty; zmiana wymaga pisemnej akceptacji.</span></li><li><b>Udokumentowany rezultat</b><span>Raport, rejestr, status bramki albo plan działania.</span></li><li><b>Zamknięcie</b><span>Formalne przekazanie i decyzja, czy potrzebny jest kolejny etap.</span></li></ol></section><section class="boundary"><p>Nie projektuję wnętrz, nie wykonuję robót i nie przejmuję odpowiedzialności innych stron. Kontroluję wyłącznie zakres zapisany w ofercie.</p></section>'''
(ROOT/'pl/proces.html').write_text(layout(lang,'Jak pracuję','Pisemny zakres, kontrolowana realizacja i udokumentowane zamknięcie.','proces.html',process),encoding='utf-8')

proof='''<header class="page-hero"><p class="eyebrow">DOWODY</p><h1>Dowody i materiały</h1><p class="lead">Zobacz format rezultatu, nie tylko deklaracje.</p></header><section><div class="cards"><article class="card"><h3>Przykładowy raport odbioru</h3><p>Status, podstawa, dowód, klasyfikacja, kolejne działanie i zamknięcie. Materiał anonimowy.</p><a class="text-link" href="/pl/sample-handover-report.html">Otwórz przykład →</a></article><article class="card"><h3>Checklista przed zaliczką</h3><p>Zakres, materiały, wymiary, odpowiedzialność, terminy, płatność, montaż i odbiór.</p><a class="text-link" href="/pl/pre-order-checklist.html">Otwórz checklistę →</a></article><article class="card"><h3>Rejestr ryzyk i decyzji</h3><p>Problem, wpływ, właściciel, termin, decyzja, dowód i status.</p><a class="text-link" href="/pl/sample-risk-register.html">Otwórz przykład →</a></article></div></section><section class="case-feature"><img src="/assets/projects/landbyska-verket/landbyska-verket-cover.webp" alt="Landbyska Verket"><div><p class="eyebrow">ZWERYFIKOWANE DOŚWIADCZENIE ZAWODOWE</p><h2>Landbyska Verket, Sztokholm</h2><p>Lead Project Manager po stronie wykonawcy zabudowy meblowej — firmy STOLPIN. Case study nie sugeruje autorstwa całego wnętrza ani niezależnej realizacji.</p><a class="text-link" href="/pl/landbyska-verket.html">Zobacz case study →</a></div></section>'''
(ROOT/'pl/dowody.html').write_text(layout(lang,'Dowody','Przykładowe rezultaty i zweryfikowane doświadczenie.','dowody.html',proof),encoding='utf-8')

common='''<input type="hidden" name="_subject" value="Nowe zapytanie ze strony — PL"><input type="hidden" name="_template" value="table"><input type="hidden" name="_captcha" value="false"><input type="text" name="_honey" class="honeypot" tabindex="-1" autocomplete="off"><input type="hidden" name="utm_source"><input type="hidden" name="utm_medium"><input type="hidden" name="utm_campaign">'''
consent='''<label class="check"><input type="checkbox" name="privacy_ack" required><span>Zapoznałem/am się z <a href="/pl/polityka-prywatnosci.html">polityką prywatności</a> i zgadzam się na kontakt w sprawie tego zapytania.</span></label>'''
b2c=f'''<header class="page-hero compact"><p class="eyebrow">B2C / ZAPYTANIE</p><h1>Opisz realizację B2C</h1><p class="lead">Konin + 50 km; dalsze lokalizacje po uzgodnieniu.</p></header><section class="form-section"><form class="lead-form" action="https://formsubmit.co/info@adam-jakubowski.com" method="POST" data-segment="B2C">{common}<input type="hidden" name="_next" value="https://adam-jakubowski.com/pl/dziekuje.html"><input type="hidden" name="segment" value="B2C"><label>Imię *<input name="name" autocomplete="name" required></label><label>E-mail *<input type="email" name="email" autocomplete="email" required></label><label>Telefon i preferowana pora kontaktu<input name="phone" autocomplete="tel"></label><label>Lokalizacja lub kod pocztowy *<input name="location" required></label><label>Etap *<select name="stage" required><option value="">Wybierz</option><option>Przed zamówieniem</option><option>W realizacji</option><option>Montaż</option><option>Odbiór</option><option>Poprawki</option></select></label><label>Rodzaj zabudowy *<input name="scope_type" required></label><label>Planowany termin *<input name="planned_date" required></label><label>Opis sytuacji i oczekiwany rezultat *<textarea name="message" rows="7" required></textarea></label><label>Skąd o mnie wiesz?<input name="source" placeholder="LinkedIn / Google / polecenie / inne"></label>{consent}<p class="fine">Na tym etapie nie przyjmuję załączników. Wysłanie formularza nie rezerwuje terminu i nie oznacza przyjęcia zlecenia.</p><button class="button" type="submit">Wyślij opis realizacji</button><p class="form-status" role="status" aria-live="polite"></p></form></section>'''
(ROOT/'pl/formularz-b2c.html').write_text(layout(lang,'Formularz B2C','Zapytanie dotyczące mebli na wymiar dla klienta prywatnego.','formularz-b2c.html',b2c),encoding='utf-8')

b2b=f'''<header class="page-hero compact"><p class="eyebrow">B2B / SCREENING</p><h1>Prześlij dane projektu B2B</h1><p class="notice">Nie załączaj NDA, rysunków, wycen ani materiałów poufnych. Najpierw sprawdzę dopasowanie i możliwy konflikt interesów.</p></header><section class="form-section"><form class="lead-form" action="https://formsubmit.co/info@adam-jakubowski.com" method="POST" data-segment="B2B">{common}<input type="hidden" name="_next" value="https://adam-jakubowski.com/pl/dziekuje.html"><input type="hidden" name="segment" value="B2B"><label>Imię i nazwisko *<input name="name" autocomplete="name" required></label><label>Firma *<input name="company" autocomplete="organization" required></label><label>Rola *<input name="role" required></label><label>E-mail służbowy *<input type="email" name="email" autocomplete="email" required></label><label>Kraj i lokalizacja projektu *<input name="location" required></label><label>Typ projektu i aktualny etap *<input name="project_stage" required></label><label>Termin krytyczny *<input name="critical_date" required></label><label>Oczekiwany rezultat *<textarea name="expected_outcome" rows="5" required></textarea></label><label>Klient, wykonawcy, producenci lub kategorie stron potrzebne do screeningu *<textarea name="screening_parties" rows="4" required></textarea></label><label>Preferowany język *<select name="language" required><option>PL</option><option>EN</option><option>DE</option></select></label><label>Źródło kontaktu<input name="source"></label><label class="check"><input type="checkbox" name="confidentiality_ack" required><span>Potwierdzam, że zgłoszenie nie zawiera nieuzgodnionych informacji poufnych.</span></label>{consent}<p class="fine">Zgłoszenie nie oznacza przyjęcia projektu ani zgody na przesłanie dokumentacji poufnej.</p><button class="button" type="submit">Wyślij dane do screeningu</button><p class="form-status" role="status" aria-live="polite"></p></form></section>'''
(ROOT/'pl/formularz-b2b.html').write_text(layout(lang,'Formularz B2B','Wstępny screening projektu meblowego lub fit-out.','formularz-b2b.html',b2b),encoding='utf-8')

privacy='''<header class="page-hero compact"><p class="eyebrow">PRYWATNOŚĆ</p><h1>Polityka prywatności</h1></header><article class="legal"><h2>Administrator i kontakt</h2><p>Adam Jakubowski, kontakt: info@adam-jakubowski.com.</p><h2>Cel i podstawa</h2><p>Dane z formularza służą odpowiedzi na zapytanie, sprawdzeniu dopasowania, dostępności oraz — dla B2B — możliwego konfliktu interesów, a także podjęciu działań przed ewentualną umową. Dane mogą być zachowane w uzasadnionym interesie ochrony roszczeń i dokumentowania decyzji konfliktowych.</p><h2>Odbiorcy danych</h2><p>Strona jest hostowana przez GitHub Pages. Formularze są przekazywane przez FormSubmit na wskazany adres e-mail. Dostawcy hostingu, formularza i poczty mogą przetwarzać dane we własnej infrastrukturze, także poza EOG. Na etapie zapytania nie przesyłaj danych wrażliwych ani dokumentów poufnych.</p><h2>Retencja</h2><p>Odrzucone zapytania: docelowo 6 miesięcy. Zapytania prowadzone: do 12 miesięcy po zamknięciu, chyba że prawo, księgowość lub roszczenia wymagają dłuższego okresu. Materiały projektowe wyłącznie przez okres niezbędny do usługi i ochrony roszczeń.</p><h2>Prawa</h2><p>Możesz żądać dostępu, sprostowania, usunięcia, ograniczenia lub wnieść sprzeciw, gdy ma zastosowanie, oraz skargę do Prezesa UODO. Kontakt: info@adam-jakubowski.com.</p><h2>Cookies i analityka</h2><p>Ta wersja nie używa cookies reklamowych ani profilowania. Treść formularzy nie jest zapisywana w pamięci lokalnej przeglądarki.</p><p class="notice">Dokument roboczy do przeglądu prawnego; wymaga aktualizacji po wyborze formy działalności, CRM, analityki lub kolejnych podmiotów przetwarzających.</p></article>'''
(ROOT/'pl/polityka-prywatnosci.html').write_text(layout(lang,'Polityka prywatności','Informacja o danych w formularzach kontaktowych.','polityka-prywatnosci.html',privacy),encoding='utf-8')

faq='''<header class="page-hero compact"><p class="eyebrow">FAQ</p><h1>Najczęstsze pytania</h1></header><section class="faq"><details><summary>Czy projektujesz meble lub wnętrza?</summary><p>Nie. Analizuję i kontroluję uzgodniony zakres realizacji; nie zastępuję projektanta ani wykonawcy.</p></details><details><summary>Czy gwarantujesz koszt, termin lub jakość?</summary><p>Nie. Dokumentuję stan, ryzyka i decyzje w zapisanym zakresie, ale nie gwarantuję wyników zależnych od innych stron.</p></details><details><summary>Jaki jest obszar usług B2C?</summary><p>Podstawowo Konin + 50 km. Dalsze lokalizacje po uzgodnieniu czasu i kosztu dojazdu.</p></details><details><summary>Czy mogę przesłać poufne dokumenty B2B?</summary><p>Nie przed screeningiem dopasowania i konfliktu. Pierwszy formularz nie przyjmuje załączników.</p></details><details><summary>Czy formularz rezerwuje termin?</summary><p>Nie. Uruchamia tylko kwalifikację. Zakres, dostępność, cena i warunki są potwierdzane osobno na piśmie.</p></details></section>'''
(ROOT/'pl/faq.html').write_text(layout(lang,'FAQ','Pytania o wsparcie przy meblach na wymiar i fit-out.','faq.html',faq),encoding='utf-8')

samples={
'sample-handover-report.html':('Przykładowy raport odbioru','''<header class="page-hero compact"><p class="eyebrow">PRZYKŁAD / ANONIMOWY</p><h1>Przykładowy raport odbioru</h1><p class="lead">Format poglądowy — nie jest raportem z projektu klienta.</p></header><article class="legal"><h2>Zakres</h2><p>Jedna zabudowa kuchenna; elementy widoczne i dostępne funkcje porównane z rysunkiem rewizja 03 i uzgodnioną specyfikacją wykończeń.</p><h2>Pozycja 01 — ustawienie frontów</h2><p><strong>Klasyfikacja:</strong> stwierdzona niezgodność. <strong>Podstawa:</strong> rysunek 03, elewacja B. <strong>Dowód:</strong> widoczna różnica linii górnej. <strong>Status:</strong> otwarte. <strong>Działanie:</strong> regulacja i zdjęcie potwierdzające.</p><h2>Pozycja 02 — podłączenie urządzenia</h2><p><strong>Klasyfikacja:</strong> niesprawdzone. Urządzenie nie było podłączone. Weryfikacja wymaga uprawnionego specjalisty.</p><h2>Zamknięcie</h2><p>12 pozycji zamkniętych, 2 otwarte, 1 niesprawdzona. Ponowna wizyta jest osobną usługą.</p></article>'''),
'pre-order-checklist.html':('Checklista przed zaliczką','''<header class="page-hero compact"><p class="eyebrow">CHECKLISTA</p><h1>Przed wpłatą zaliczki</h1></header><article class="legal"><h2>Zakres i dokumenty</h2><p>☐ Dokładna lista mebli i elementów<br>☐ Aktualna rewizja rysunków i wymiary<br>☐ Materiały, dekory, obrzeża, okucia i urządzenia<br>☐ Elementy wyłączone z oferty</p><h2>Odpowiedzialność</h2><p>☐ Kto mierzy i zatwierdza wymiary<br>☐ Kto przygotowuje instalacje i miejsce montażu<br>☐ Kto koordynuje inne branże<br>☐ Kto zatwierdza zmiany i dodatkowe koszty</p><h2>Termin i odbiór</h2><p>☐ Daty produkcji, dostawy i montażu<br>☐ Warunki zmiany terminu<br>☐ Sposób odbioru i lista usterek<br>☐ Gwarancja, serwis i reklamacje</p></article>'''),
'sample-risk-register.html':('Przykładowy rejestr ryzyk','''<header class="page-hero compact"><p class="eyebrow">PRZYKŁAD / ANONIMOWY</p><h1>Rejestr ryzyk i decyzji</h1></header><article class="legal"><h2>R-01 — brak akceptacji wykończenia</h2><p><strong>Wpływ:</strong> blokada uruchomienia produkcji. <strong>Właściciel:</strong> osoba decyzyjna klienta. <strong>Status:</strong> otwarte. <strong>Decyzja:</strong> wybór próbki A lub B.</p><h2>R-02 — miejsce niegotowe</h2><p><strong>Wpływ:</strong> brak bezpiecznego startu montażu. <strong>Właściciel:</strong> wykonawca główny. <strong>Status:</strong> warunkowe.</p><h2>D-01 — bramka wysyłki</h2><p><strong>Decyzja:</strong> warunkowe „go” po zamknięciu R-01 i pisemnym potwierdzeniu dostępu.</p></article>''')}
for slug,(title,body) in samples.items():
    (ROOT/'pl'/slug).write_text(layout(lang,title,'Anonimowy przykład rezultatu usługi.',slug,body),encoding='utf-8')

# Root mirrors final Polish homepage after all overrides.
(ROOT/'index.html').write_text((ROOT/'pl/index.html').read_text(encoding='utf-8').replace('href="/pl/"','href="/"',1).replace('https://adam-jakubowski.com/pl/','https://adam-jakubowski.com/'),encoding='utf-8')
print('Polish localization overrides generated')
